version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 61613
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      MONGODB_URI: "mongodb://mongodb:27017/test"
    ports:
      - 8080:8080
    volumes:
      - .:/app/

  rabbitmq:
    build: ./rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 15672:15672
      - 5672:5672
      - 61613:61613

  mongodb:
    image: mongo:3.2
    ports:
      - 27017:27017
